---
# This will install Postgres
- name: install the postgres rpm from a remote repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
    state: present


- name: Install Postgres package
  yum: name={{ item }} state=installed
  with_items:
    - postgresql96-server 
    - postgresql96-contrib

- name: Copy db_init
  copy: src=../files/db_init.sh dest=/tmp/db_init.sh

- name: Execute db_init
  command: /tmp/db_init.sh

- name: create replication account
  command: sudo su postgres -c 'psql -c "create user replicador replication;"'

- name: Modfiy db config files
  copy: src=../files/modify_db_cfg.sh dest=/tmp/modify_db_cfg.sh

- name: Execute modify db config
  command: /tmp/modify_db_cfg.sh
