---
# This will install Postgres
- name: install the postgres rpm from a remote repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
    state: present


- name: Install Postgres package
  yum: name={{ item }} state=installed
  with_items:
    - postgresql96-server 
    - postgresql96-contrib

- name: run pginit scripts

- name: create replication account
  command: sudo su postgres -c 'psql -c "create user replicador replication;"'

